# github
name: Build Docker & Push Private Registry
# 触发时机：main分支推送、tag打版本
on:
  push:
    branches: [ dev ]
    tags: [ 'v*' ]
  # 手动触发配置，可自定义镜像tag
  workflow_dispatch:
    inputs:
      custom_tag:
        description: 自定义镜像Tag（手动构建时填写，不填默认使用commit短哈希）
        required: false
        default: ""
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # 1. 拉取代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 配置Docker Buildx（加速构建、支持多架构）
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. 登录私有镜像仓库
      - name: Login Private Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_REGISTRY }}
          username: ${{ secrets.ACR_USER }}
          password: ${{ secrets.ACR_PWD }}

      # 4. 判断触发方式，生成对应镜像标签
      - name: Generate Image Tag
        id: meta
        run: |
          # 手动触发且输入了自定义tag，优先使用自定义值
          if [[ "${{ github.event_name }}" == "workflow_dispatch" && -n "${{ github.event.inputs.custom_tag }}" ]]; then
            echo "TAG=${{ github.event.inputs.custom_tag }}" >> $GITHUB_ENV
          # git推送版本tag（v1.0.0）
          elif [[ "${{ github.ref }}" == refs/tags/* ]]; then
            echo "TAG=${{ github.ref_name }}" >> $GITHUB_ENV
          # 普通代码提交，使用git短commit哈希
          else
            echo "TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          fi

      # 5. 构建并推送镜像
      - name: Build & Push Image
        uses: docker/build-push-action@v6
        with:
          context: .
          # 镜像全称：仓库地址/项目名:标签
          tags: ${{ secrets.ACR_REGISTRY }}/zchimp/kubegraph:${{ env.TAG }},${{ secrets.ACR_REGISTRY }}/zchimp/kubegraph:latest
          push: true
